### ISSUE TITLE
Do the package have Tencent TBS SDK?

### ISSUE THREAD

**Issue by Chinna2405** [sidsbrmnn/jwt_decode#15]
Hi,

Do the package have Tencent TBS SDK?

**Comment by Bidhanrai** [comment]
Is there any problem while releasing app using this plugin in playstore/appstore?

**Comment by sidsbrmnn** [comment]
> Hi,
> 
> Do the package have Tencent TBS SDK?

Highly unlikely as the library is written purely in dart without any third-party dependencies.
