### ISSUE TITLE
Tests fails in non UTC+05:30 timezone

### ISSUE THREAD

**Issue by mingulov** [sidsbrmnn/jwt_decode#9]
getExpiryDate uses DateTime.fromMillisecondsSinceEpoch without isUtc=true (it is false by default), and currently the comparison in test is done with hard-coded UTC+05:30 time, so it fails in other timezones, for example:

```
$ flutter test
00:01 +1 -1: getting expiry date [E]                                                                                                                                                          
  Expected: DateTime:<2021-12-22 01:46:13.000>
    Actual: DateTime:<2021-12-21 22:16:13.000>
  
  package:test_api                expect
  test/jwt_decode_test.dart 26:5  main.<fn>
  
00:01 +2 -1: Some tests failed.               
```

**Comment by sidsbrmnn** [comment]
The `iat` and `exp` claims are seconds from epoch and do not include UTC timezones. Yes, the test cases could be written in a "not hardcoded" manner, but it still works. It will fail if you enable UTC timezone checks. You can refer to the RFC for JWTs and the way these 2 claims are used in them.

<img width="682" alt="Screenshot 2021-03-23 at 11 12 31 PM" src="https://user-images.githubusercontent.com/35731243/112192747-412fca00-8c2d-11eb-9e3e-537a6248f643.png">

The tests work for me without any changes.

**Comment by sidsbrmnn** [comment]
You're right! I'll need to change the expiration checking using `isUtc: true` and also change the test case accordingly.
